dist: bionic
language: c
before_install:
  - sudo apt-get -y --no-install-recommends install postgresql-11 postgresql-server-dev-11
  - sudo pkill -9 postgres || true
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

compiler:
  - clang
  - gcc
script:
  - cmake -DCMAKE_BUILD_TYPE=Release
  - make -j2
  - cd test
  - "./odyssey_test"
  - cd ..
before_deploy:
  - tar -zcf odyssey.linux-amd64.$(git rev-parse --short HEAD).tar.gz -C sources odyssey
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wg142d0buOd42WmPcQyZRFlfpuNAcQV2zhWr3h4hLMd43blgJho/9D13N4fAr/pY83MbZ9Fssp2KX2ukI7jX/mY62Fq8e7vlAeH5gNRxKmDrj8YyRRqCYxugSGmMmmV3iOYGehN32xO54YOnuq8Gi86wzUPS2+oQMIOGer6+xlcwib58ytygUqLQ8wz/fzGbEwTgmuBtI6mroeAEQF6vWqNtfw4wcmchnjiJ3BoJDPa6XyeiMtsPW9wgACHOFWBsf9bsmrxJ56mknyS5jyfltAIU6USGIq4fc0hdfyj4IFMUaBSf8q3mU0rRED4JKv0wihyWwPTwbWJPySWqR1zFDV2VHHj8yMdds3bf4UKE4v6FIfp/r7WQA3GUAibAPbOfcK/WuR2/4nXFYxkJmsJBIht3rKJ+2Tm6MowDlJf95a8qDqT+iG2J2yr2GCLpmeYzLVCsoTDiQP0SahGz9QsHuMoviS4RqT8hYlZSqj1b1LnrZeEvR4FUgkOiqFs4PbevAlBJjyeBex72GTamAsdc2TWbIbDtQ1+Y9pZVRDLaJPOZCrc5LNHLZHj+T2pRuPEEQNRHqvSVAYTOn0t7cUzmXYcM4ggqN0s7ZhQm3aRK0GpUBQhNdWkDWy3b8Mk7rFqZ8GyaNNvBhUlo+Gx/6vfr6MypxEMHKpcAHV1gY+qKapE=
  file: odyssey.linux-amd64.$(git rev-parse --short HEAD).tar.gz
  on:
    repo: yandex/odyssey
    tags: true
env:
  global:
    - secure: "TKTVDz3HTTVyapdh2VUnXnjXbIv123OnFFtBkko7ps5PWri/Y02NJ741nhtJwEn+cq6mFuX/qGYYNIhK99x7k/+eiVug9nNoVal4Ug2KuM4J6vjYGQRkv51qeO2W3BOnqjqji7VSzuOF38jZHnITwBbKEAmPE5G2OCgsd3DjaazECr9ZMONRzaCTIB/qxHlQO5RiEyIDqBboSDU9Z4u28rqzTYZazcZvifL8+K/9msRDi3iXqE2qtzwn8iv3XLl+p6mTZqFEEuGe+Lte1Ji3CyGTlBcIim34mxxtJDzY9pECAIz2B8Or3g8ubvVSLrGgFbBoL1Ne73NHW8UppkB9JnVQzCC0JaHndZusxs9F6KtAiOEhcgKkZS7zVOOgLM41FomdHwG3HkpYYCfWnVIPejOsqkHPgkWJEAPOWm6vb/uz3r5k3WnQ/XJTJMc0Jn022FnoR7xByi0/wq8OlNHyyHkerBo87ybeCy0x/UZrga4pE0LT6jaw6tEG/9jaIck+C/MHF0UN6f0QJmY0bjnnirAntN16//EWiPXeT22VQgPzEm4v2xgdCmjxeuvLSlUfwurT5grj44sPdytyitkRVpzP477p+Aku/wQ/m/UNbIzE3ujC2KIA+TMxGu1BnQCRDS0GrgLB6t4Yq7amQQyg98ShE4RJBoUFRYbqAAX5znM="

addons:
  coverity_scan:
    project:
      name: "yandex/odyssey"
      description: "Advanced multi-threaded PostgreSQL connection pooler and request router."
    notification_email: amborodin@acm.org
    build_command_prepend: "cmake -DCMAKE_BUILD_TYPE=Release"
    build_command: "make -j2"
    branch_pattern: coverity_scan
