services:
  odyssey:
    extra_hosts:
      - "ip4-localhost:127.0.0.1"
    ulimits:
      core:
        soft: -1
        hard: -1
    privileged: true
    build:
      dockerfile: ./docker/functional/Dockerfile
      context: ../../ # odyssey root dir
      no_cache: true
      target: "${ODYSSEY_TEST_TARGET:-functional-entrypoint}"
      args:
        odyssey_build_type: "${ODYSSEY_FUNCTIONAL_BUILD_TYPE:-build_release}"
    environment:
      CMAKE_BUILD_TYPE: "${CMAKE_BUILD_TYPE:-Debug}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
      - "7777:7777"
    networks:
      od_net:
        ipv4_address: 192.168.233.15

  openldapr:
    image: "osixia/openldap:1.5.0"
    networks:
      od_net:
        ipv4_address: 192.168.233.16

networks:
  od_net:
    name: odyssey_od_net
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 192.168.233.0/24
         #       - gateway: 192.168.233.1
