name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu-build:
    name: ubuntu-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-version: ['jammy', 'noble']
        pg-version: ['14', '17']
        build-type: ['build_release']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Ubuntu build check
      run: make ci-build-check-ubuntu ODYSSEY_BUILD_TYPE=${{ matrix.build-type }} ODYSSEY_POSTGRES_VERSION=${{ matrix.pg-version }} ODYSSEY_TEST_CODENAME=${{ matrix.os-version }}
  fedora-build:
    name: fedora-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Fedora build check
      run: make ci-build-check-fedora
