name: Drivers tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/**"
      - "test/**"
      - "CMakeLists.txt"
      - "docker/**"
      - "modules/**"
      - "cmake/**"
      - "!docker/prom-exporter/**"
jobs:
  jdbc:
    name: jdbc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Odyssey JDBC compatibility tests
      run: make jdbc_test
