name: Unit tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/**"
      - "test/**"
      - "docker/**"
      - "modules/**"
      - "cmake/**"
      - "!docker/prom-exporter/**"
jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: ['build_release', 'build_dbg', 'build_asan']
        target-arch: ['linux/amd64']
        cc: ['gcc', 'clang']
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: qemu setup
      uses: docker/setup-qemu-action@v3
    - name: docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Odyssey unit tests
      run: make ci-unittests ODYSSEY_BUILD_TYPE=${{ matrix.build-type }} ODYSSEY_TEST_TARGET_PLATFORM=${{ matrix.target-arch }} ODYSSEY_CC=${{ matrix.cc }}
